#!/usr/bin/env node

/**
 * Setup script to create .env file for backend server
 * Run: node setup-env.js
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const envExamplePath = path.join(__dirname, '.env.example');

// Check if .env already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env file already exists!');
  console.log('If you want to recreate it, delete .env first and run this script again.');
  process.exit(0);
}

// Create .env file with API keys
const envContent = `# Backend Environment Variables
# Generated by setup-env.js
# DO NOT commit this file to version control

# API Keys (Required)
OPENROUTER_API_KEY=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
MISTRAL_API_KEY=e5feb740-569e-47d8-bf3e-3f0a1e359862

# Server Configuration
PORT=5000
NODE_ENV=development

# CORS Configuration (comma-separated URLs)
# For production, include your Firebase Hosting URLs
FRONTEND_URL=http://localhost:5173,http://localhost:3000,https://aira-learning-a3884.web.app,https://aira-learning-a3884.firebaseapp.com

# AI Provider Configuration
AI_PROVIDER=openrouter
OPENROUTER_MODEL=qwen/qwen-2.5-7b-instruct
MISTRAL_MODEL=mistral-small-latest
DOUBT_RESOLUTION_MODEL=llama

# Timeout Configuration
AI_REQUEST_TIMEOUT_MS=60000
`;

try {
  fs.writeFileSync(envPath, envContent, 'utf8');
  console.log('✅ .env file created successfully!');
  console.log('📝 Location: backend/.env');
  console.log('');
  console.log('Next steps:');
  console.log('1. Install dependencies: npm install');
  console.log('2. Start server: npm run dev');
  console.log('3. Test: curl http://localhost:5000/health');
} catch (error) {
  console.error('❌ Error creating .env file:', error.message);
  process.exit(1);
}
