# PowerShell script to create .env file for backend
# Run: .\setup-env.ps1

$envPath = Join-Path $PSScriptRoot ".env"

# Check if .env already exists
if (Test-Path $envPath) {
    Write-Host "⚠️  .env file already exists!" -ForegroundColor Yellow
    $response = Read-Host "Do you want to overwrite it? (y/n)"
    if ($response -ne 'y' -and $response -ne 'Y') {
        Write-Host "Cancelled." -ForegroundColor Yellow
        exit 0
    }
}

# Create .env file content
$envContent = @"
# Backend Environment Variables
# Generated by setup-env.ps1
# DO NOT commit this file to version control

# API Keys (Required)
OPENROUTER_API_KEY=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
MISTRAL_API_KEY=e5feb740-569e-47d8-bf3e-3f0a1e359862

# Server Configuration
PORT=5000
NODE_ENV=development

# CORS Configuration (comma-separated URLs)
# For production, include your Firebase Hosting URLs
FRONTEND_URL=http://localhost:5173,http://localhost:3000,https://aira-learning-a3884.web.app,https://aira-learning-a3884.firebaseapp.com

# AI Provider Configuration
AI_PROVIDER=openrouter
OPENROUTER_MODEL=qwen/qwen-2.5-7b-instruct
MISTRAL_MODEL=mistral-small-latest
DOUBT_RESOLUTION_MODEL=llama

# Timeout Configuration
AI_REQUEST_TIMEOUT_MS=60000
"@

try {
    $envContent | Out-File -FilePath $envPath -Encoding utf8 -NoNewline
    Write-Host "✅ .env file created successfully!" -ForegroundColor Green
    Write-Host "📝 Location: $envPath" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "1. Install dependencies: npm install"
    Write-Host "2. Start server: npm run dev"
    Write-Host "3. Test: curl http://localhost:5000/health"
} catch {
    $errorMsg = $_.Exception.Message
    Write-Host "❌ Error creating .env file: $errorMsg" -ForegroundColor Red
    exit 1
}
