import type { VisualProps } from './topicVisuals';
import {
    ACCircuitVisual,
    APIDesignVisual,
    AnxietyVisual,
    BloodFlowVisual,
    BrainStructureVisual,
    CBTVisual,
    CellStructureVisual,
    ContractFormationVisual,
    CoronaryArteriesVisual,
    DCCircuitVisual,
    DefaultTopicVisual,
    DNAReplicationVisual,
    DNAStructureVisual,
    DNATranscriptionVisual,
    DNATranslationVisual,
    ECGBasicsVisual,
    EncryptionVisual,
    GraphVisualizationVisual,
    HeartValvesVisual,
    HeredityVisual,
    KinematicsVisual,
    NeuralNetworkVisual,
    NeuronVisual,
    NewtonsLawsVisual,
    ReactComponentVisual,
    SEOVisual,
    SortingAlgorithmVisual,
    SpinalCordVisual,
    SQLBasicsVisual,
    StockMarketVisual,
    StrokeVisual,
    SupervisedLearningVisual,
    ThermodynamicsVisual,
} from './topicVisuals';

type VisualComponent = (props: VisualProps) => JSX.Element;

const TopicVisualRegistry: Record<string, VisualComponent> = {
    'heart-structure': HeartValvesVisual,
    'valves': HeartValvesVisual,
    'blood-flow': BloodFlowVisual,
    'coronary-arteries': CoronaryArteriesVisual,
    'ecg-basics': ECGBasicsVisual,
    'echo': ECGBasicsVisual,
    'stress-test': ECGBasicsVisual,
    'arrhythmias': ECGBasicsVisual,
    'heart-failure': BloodFlowVisual,
    'brain-structure': BrainStructureVisual,
    'neurons': NeuronVisual,
    'spinal-cord': SpinalCordVisual,
    'stroke': StrokeVisual,
    'epilepsy': BrainStructureVisual,
    'cancer-biology': CellStructureVisual,
    'staging': CellStructureVisual,
    'milestones': DefaultTopicVisual,
    'vaccines': DefaultTopicVisual,
    'react-basics': ReactComponentVisual,
    'state-management': ReactComponentVisual,
    'api-design': APIDesignVisual,
    'sorting': SortingAlgorithmVisual,
    'graphs': GraphVisualizationVisual,
    'dynamic-programming': GraphVisualizationVisual,
    'sql-basics': SQLBasicsVisual,
    'nosql': GraphVisualizationVisual,
    'laws-thermo': ThermodynamicsVisual,
    'heat-transfer': ThermodynamicsVisual,
    'entropy': ThermodynamicsVisual,
    'statics': NewtonsLawsVisual,
    'dynamics': KinematicsVisual,
    'dc-circuits': DCCircuitVisual,
    'ac-circuits': ACCircuitVisual,
    'beams': NewtonsLawsVisual,
    'foundations': NewtonsLawsVisual,
    'contract-formation': ContractFormationVisual,
    'breach': ContractFormationVisual,
    'remedies': ContractFormationVisual,
    'directors': ContractFormationVisual,
    'shareholders': ContractFormationVisual,
    'investigation': ContractFormationVisual,
    'trial': ContractFormationVisual,
    'sentencing': ContractFormationVisual,
    'mens-rea': ContractFormationVisual,
    'defenses': ContractFormationVisual,
    'first-amendment': ContractFormationVisual,
    'due-process': ContractFormationVisual,
    'seo': SEOVisual,
    'social-media': SEOVisual,
    'content-marketing': SEOVisual,
    'brand-identity': SEOVisual,
    'positioning': SEOVisual,
    'stocks': StockMarketVisual,
    'bonds': StockMarketVisual,
    'portfolio': StockMarketVisual,
    'financial-statements': StockMarketVisual,
    'ratio-analysis': StockMarketVisual,
    'leadership-styles': SEOVisual,
    'team-building': SEOVisual,
    'newtons-laws': NewtonsLawsVisual,
    'kinematics': KinematicsVisual,
    'energy': ThermodynamicsVisual,
    'electric-fields': ACCircuitVisual,
    'magnetic-fields': ACCircuitVisual,
    'dna-structure': DNAStructureVisual,
    'dna-replication': DNAReplicationVisual,
    'replication': DNAReplicationVisual,
    'transcription': DNATranscriptionVisual,
    'translation': DNATranslationVisual,
    'heredity': HeredityVisual,
    'gene-expression': DNATranscriptionVisual,
    'cell-structure': CellStructureVisual,
    'cell-division': CellStructureVisual,
    'hydrocarbons': DNAStructureVisual,
    'functional-groups': DNAStructureVisual,
    'renaissance': DefaultTopicVisual,
    'modernism': DefaultTopicVisual,
    'contemporary': DefaultTopicVisual,
    'color-theory': DefaultTopicVisual,
    'composition': DefaultTopicVisual,
    'narrative': DefaultTopicVisual,
    'themes': DefaultTopicVisual,
    'supervised': SupervisedLearningVisual,
    'neural-networks': NeuralNetworkVisual,
    'unsupervised': SupervisedLearningVisual,
    'text-processing': SupervisedLearningVisual,
    'transformers': NeuralNetworkVisual,
    'firewalls': EncryptionVisual,
    'encryption': EncryptionVisual,
    'penetration': EncryptionVisual,
    'symmetric': EncryptionVisual,
    'asymmetric': EncryptionVisual,
    'ec2': SupervisedLearningVisual,
    's3': SupervisedLearningVisual,
    'active-learning': SEOVisual,
    'assessment': SEOVisual,
    'differentiation': SEOVisual,
    'learning-objectives': SEOVisual,
    'backward-design': SEOVisual,
    'iep': SEOVisual,
    'accommodations': SEOVisual,
    'anxiety': AnxietyVisual,
    'depression': AnxietyVisual,
    'ptsd': AnxietyVisual,
    'cbt': CBTVisual,
    'psychodynamic': CBTVisual,
    'memory-types': BrainStructureVisual,
    'forgetting': BrainStructureVisual,
};

export function getTopicVisual(topicId: string): VisualComponent {
    return TopicVisualRegistry[topicId] || DefaultTopicVisual;
}
